apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: multi-containers-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: multi-containers-deployment
    spec:
      containers:
      - name: hello-node-container
        image: hello-node-kube-docker-image:v1
        ports:
        - containerPort: 8080
      - name: app2-invoke-container
        image: app2-invoke-docker-image:v1
        ports:
        - containerPort: 8081
